window.ARTIFACTS_LIBRARY = {
    totalArtifacts: 16,
    hostPage: '/ferramentas/artefato.html',
    categories: [
        {
            slug: 'conjuntos',
            title: 'Conjuntos',
            accent: 'blue',
            description: 'Modelos que ajudam a visualizar pertinencia, operacoes entre conjuntos e a ideia de agrupamento.',
        },
        {
            slug: 'conjuntos-numericos',
            title: 'Conjuntos Numéricos',
            accent: 'green',
            description: 'Ferramentas para classificar números, enxergar a hierarquia N-Z-Q-R e testar exemplos rapidamente.',
        },
        {
            slug: 'ordem-e-intervalos',
            title: 'Ordem e Intervalos',
            accent: 'amber',
            description: 'Visualizações para desigualdades, reta real e leitura correta de intervalos abertos, fechados e semiabertos.',
        },
        {
            slug: 'algebra',
            title: 'Álgebra',
            accent: 'blue',
            description: 'Materiais visuais que aproximam propriedades algébricas de superfícies, padrões e organizadores de estudo.',
        },
        {
            slug: 'produtos-notaveis',
            title: 'Produtos Notáveis',
            accent: 'amber',
            description: 'Explorações para entender de onde surgem os termos dos quadrados e cubos notáveis.',
        },
        {
            slug: 'fatoracao',
            title: 'Fatoração',
            accent: 'red',
            description: 'Ferramentas para voltar da expressão expandida aos fatores e acompanhar passos de fatoração.',
        },
        {
            slug: 'bhaskara',
            title: 'Bhaskara e Parábolas',
            accent: 'red',
            description: 'Explorações complementares de equação do 2º grau, discriminante e relação entre raízes e gráfico.',
        },
    ],
    items: [
        {
            slug: 'diagrama-venn-interativo',
            file: 'diagrama_venn_interativo.html',
            title: 'Diagrama de Venn interativo',
            category: 'conjuntos',
            accent: 'blue',
            priority: 'high',
            moduleSlugs: ['conjuntos'],
            summary: 'Monte dois conjuntos, adicione elementos e veja em tempo real a união, a interseção e as diferenças.',
            teaches: 'Leitura das operações entre conjuntos e interpretação visual do resultado.',
            whenToUse: 'Depois de estudar união, interseção e diferença.',
            observe: 'Compare como a região destacada muda quando você alterna a operação ou modifica os elementos.',
            hint: 'Experimente começar com conjuntos que compartilham alguns elementos e depois teste conjuntos sem interseção.',
            height: 520,
        },
        {
            slug: 'conjuntos-3d-esferas',
            file: 'conjuntos_3d_esferas.html',
            title: 'Conjuntos numéricos em esferas 3D',
            category: 'conjuntos-numericos',
            accent: 'green',
            priority: 'medium',
            moduleSlugs: ['conjuntos', 'conjuntos-numericos'],
            summary: 'Uma visualização espacial dos conjuntos numéricos ajuda a reforçar a ideia de inclusão entre N, Z, Q e R.',
            teaches: 'Hierarquia e abrangência dos principais conjuntos numéricos.',
            whenToUse: 'Quando quiser revisar rapidamente quem contém quem.',
            observe: 'Ative cada camada e note como os subconjuntos ficam encaixados em estruturas maiores.',
            hint: 'Use no desktop para explorar com mais conforto, mas o material continua funcional no celular.',
            height: 560,
        },
        {
            slug: 'conjuntos-e-numeros',
            file: 'conjuntos_e_numeros.html',
            title: 'Painel de conjuntos e números',
            category: 'conjuntos-numericos',
            accent: 'green',
            priority: 'medium',
            moduleSlugs: ['conjuntos', 'conjuntos-numericos'],
            summary: 'Reúne hierarquia dos conjuntos numéricos, operações entre conjuntos e um atalho para classificar números.',
            teaches: 'Conexão entre teoria de conjuntos e classificação numérica.',
            whenToUse: 'Para revisar bases antes de um quiz ou antes de mudar de módulo.',
            observe: 'Use o painel de classificação para gerar uma dúvida concreta e depois aprofunde no tutor.',
            hint: 'É um bom ponto de transição entre o módulo de conjuntos e o de conjuntos numéricos.',
            height: 540,
        },
        {
            slug: 'mapa-mental-numeros',
            file: 'mapa_mental_numeros.html',
            title: 'Mapa mental dos números',
            category: 'conjuntos-numericos',
            accent: 'green',
            priority: 'high',
            moduleSlugs: ['conjuntos-numericos'],
            summary: 'Um mapa navegável dos números reais até exemplos clássicos como π, e e √2.',
            teaches: 'Relação entre naturais, inteiros, racionais, irracionais e reais com exemplos visuais.',
            whenToUse: 'Quando a classificação estiver confusa ou você quiser revisar exemplos típicos.',
            observe: 'Clique nos nós para ver definições, exemplos e atalhos de estudo por subconjunto.',
            hint: 'Ótimo para começar o módulo e construir um panorama antes de resolver exercícios.',
            height: 620,
        },
        {
            slug: 'quiz-conjuntos-numericos',
            file: 'quiz_conjuntos_numericos.html',
            title: 'Quiz visual de conjuntos numéricos',
            category: 'conjuntos-numericos',
            accent: 'green',
            priority: 'high',
            moduleSlugs: ['conjuntos-numericos'],
            summary: 'Um quiz interno do laboratório para reforçar classificação, hierarquia e operações simples.',
            teaches: 'Fixação rápida com feedback imediato.',
            whenToUse: 'Depois de revisar teoria ou antes do quiz principal do módulo.',
            observe: 'Leia a explicação após cada resposta para entender o erro, não só para contar acertos.',
            hint: 'Use como aquecimento antes de partir para o quiz maior da plataforma.',
            height: 560,
        },
        {
            slug: 'intervalos-reta-real',
            file: 'intervalos_reta_real.html',
            title: 'Tipos de intervalo na reta real',
            category: 'ordem-e-intervalos',
            accent: 'amber',
            priority: 'high',
            moduleSlugs: ['ordem-e-intervalos'],
            summary: 'Mostra os tipos de intervalo e ainda permite variar os extremos para enxergar a notação e a desigualdade correspondente.',
            teaches: 'Relação entre notação de intervalo, desigualdade e representação gráfica.',
            whenToUse: 'Logo após aprender intervalos abertos, fechados e semiabertos.',
            observe: 'Veja como a notação e os extremos mudam juntos quando você move os controles.',
            hint: 'Conferir o lado aberto e o lado fechado separadamente reduz muitos erros.',
            height: 680,
        },
        {
            slug: 'reta-real-construtor',
            file: 'reta_real_construtor.html',
            title: 'Construtor de reta real',
            category: 'ordem-e-intervalos',
            accent: 'amber',
            priority: 'high',
            moduleSlugs: ['ordem-e-intervalos'],
            summary: 'Arraste os extremos, escolha o tipo do intervalo e teste se valores pertencem ou não ao conjunto.',
            teaches: 'Pertencimento, leitura de extremos e interpretação operacional da reta real.',
            whenToUse: 'Quando você já entende a notação e quer treinar leitura fina.',
            observe: 'Teste números específicos para verificar se pertencem ao intervalo montado.',
            hint: 'É especialmente útil para revisar porque liga notação, gráfico e teste de pertencimento.',
            height: 640,
        },
        {
            slug: 'reta-real-3d',
            file: 'reta_real_3d.html',
            title: 'Reta real 3D',
            category: 'ordem-e-intervalos',
            accent: 'amber',
            priority: 'medium',
            moduleSlugs: ['ordem-e-intervalos'],
            summary: 'Uma exploração espacial da reta real para reforçar abertura, fechamento e semirretas.',
            teaches: 'Interpretação geométrica de intervalos e semirretas.',
            whenToUse: 'Depois do construtor tradicional, como aprofundamento visual.',
            observe: 'Troque o tipo do intervalo e compare como a marcação muda nos extremos.',
            hint: 'No celular funciona, mas a exploração fica mais rica no desktop.',
            height: 600,
        },
        {
            slug: 'algebra-3d-superficie',
            file: 'algebra_3d_superficie.html',
            title: 'Superfícies algébricas 3D',
            category: 'algebra',
            accent: 'blue',
            priority: 'medium',
            moduleSlugs: ['algebra'],
            summary: 'Transforma fórmulas algébricas em superfícies para mostrar como pequenas mudanças geram comportamentos diferentes.',
            teaches: 'Intuição visual sobre expressões quadráticas e cúbicas.',
            whenToUse: 'Como aprofundamento depois de dominar a distributiva e os padrões básicos.',
            observe: 'Compare como quadrados, diferenças e cubos mudam a forma da superfície.',
            hint: 'Use para criar intuição, não para decorar fórmula isoladamente.',
            height: 620,
        },
        {
            slug: 'algebra-produtos-fatoracao',
            file: 'algebra_produtos_fatoracao.html',
            title: 'Mapa combinado de álgebra, produtos e fatoração',
            category: 'algebra',
            accent: 'blue',
            priority: 'medium',
            moduleSlugs: ['algebra', 'produtos-notaveis', 'fatoracao'],
            summary: 'Um painel de revisão rápida que junta propriedades algébricas, produtos notáveis e técnicas de fatoração.',
            teaches: 'Relação entre expandir, fatorar e reconhecer estruturas.',
            whenToUse: 'No fechamento da trilha algébrica ou na revisão de véspera.',
            observe: 'Use as abas para perceber como os tópicos se conectam em vez de estudá-los de forma isolada.',
            hint: 'Bom recurso-ponte entre os módulos de álgebra, produtos notáveis e fatoração.',
            height: 720,
        },
        {
            slug: 'expansor-produtos-notaveis',
            file: 'expansor_produtos_notaveis.html',
            title: 'Expansor de produtos notáveis',
            category: 'produtos-notaveis',
            accent: 'amber',
            priority: 'high',
            moduleSlugs: ['produtos-notaveis'],
            summary: 'Escolha a fórmula, digite valores ou expressões e acompanhe a expansão passo a passo.',
            teaches: 'Reconhecimento de padrões e expansão estruturada.',
            whenToUse: 'Quando você quer conferir de onde sai cada termo da expressão expandida.',
            observe: 'Troque entre quadrado da soma, quadrado da diferença, produto da soma pela diferença e cubos.',
            hint: 'Excelente para revisar a presença do termo do meio e evitar expansionismo no automático.',
            height: 620,
        },
        {
            slug: 'cubo-soma-3d',
            file: 'cubo_soma_3d.html',
            title: 'Cubo da soma em 3D',
            category: 'produtos-notaveis',
            accent: 'amber',
            priority: 'medium',
            moduleSlugs: ['produtos-notaveis'],
            summary: 'Explode e recompõe as peças do cubo para enxergar geometricamente o desenvolvimento de (a+b)^3.',
            teaches: 'Origem geométrica dos termos do cubo da soma.',
            whenToUse: 'Depois de estudar o cubo da soma no papel.',
            observe: 'Preste atenção em quantas peças iguais aparecem e como isso justifica os coeficientes.',
            hint: 'Esse tipo de visualização é ideal para entender por que surgem os termos com fator 3.',
            height: 560,
        },
        {
            slug: 'area-model-fatoracao',
            file: 'area_model_fatoracao.html',
            title: 'Area model para fatoração e produtos',
            category: 'produtos-notaveis',
            accent: 'amber',
            priority: 'high',
            moduleSlugs: ['produtos-notaveis', 'fatoracao'],
            summary: 'Mostra modelos de área para distributiva, quadrado da soma e diferença de quadrados.',
            teaches: 'Conexão visual entre área, distributiva, expansão e fatoração.',
            whenToUse: 'Quando você quer entender por que o termo 2ab aparece ou por que a diferença de quadrados funciona.',
            observe: 'Compare como o mosaico muda entre distributiva simples, quadrado da soma e produto da soma pela diferença.',
            hint: 'Ótimo para explicar de forma concreta os produtos notáveis antes de decorar as fórmulas.',
            height: 600,
        },
        {
            slug: 'fatorador-visual',
            file: 'fatorador_visual.html',
            title: 'Fatorador visual',
            category: 'fatoracao',
            accent: 'red',
            priority: 'high',
            moduleSlugs: ['fatoracao'],
            summary: 'Escolha a técnica de fatoração e acompanhe os passos para fator comum, diferença de quadrados, agrupamento e mais.',
            teaches: 'Tomada de decisão sobre qual técnica de fatoração usar.',
            whenToUse: 'Quando a dificuldade está em reconhecer o tipo da fatoração.',
            observe: 'Troque a técnica e compare o padrão que justifica cada caso.',
            hint: 'Use esse recurso depois de tentar sozinho: ele ajuda a enxergar o padrão que faltou.',
            height: 620,
        },
        {
            slug: 'bhaskara-animado',
            file: 'bhaskara_animado.html',
            title: 'Bhaskara animado',
            category: 'bhaskara',
            accent: 'red',
            priority: 'high',
            moduleSlugs: [],
            summary: 'Controle os coeficientes a, b e c, veja o discriminante mudar e acompanhe a resolução passo a passo.',
            teaches: 'Leitura do discriminante, cálculo das raízes e relação com o gráfico da parábola.',
            whenToUse: 'Como trilha complementar depois da base algébrica.',
            observe: 'Veja como o valor de Δ altera a quantidade de raízes reais.',
            hint: 'Mesmo fora dos módulos atuais, é um excelente avanço para quem já domina fatoração e quer seguir estudando.',
            height: 620,
        },
        {
            slug: 'parabola-raizes-3d',
            file: 'parabola_raizes_3d.html',
            title: 'Parábola e raízes em 3D',
            category: 'bhaskara',
            accent: 'red',
            priority: 'medium',
            moduleSlugs: [],
            summary: 'Uma exploração tridimensional da parábola e dos pontos onde ela encontra o eixo das raízes.',
            teaches: 'Ligação entre expressão quadrática, gráfico e raízes.',
            whenToUse: 'Depois do Bhaskara animado, como aprofundamento gráfico.',
            observe: 'Altere os coeficientes e compare quando a curva toca, cruza ou não cruza o eixo.',
            hint: 'Material complementar ideal para fechar a ponte entre álgebra e geometria analítica.',
            height: 620,
        },
    ],
    pedagogyBySlug: {
        'diagrama-venn-interativo': {
            whyHere: 'Este artefato entra no modulo de conjuntos para transformar uniao, intersecao e diferenca em leitura visual imediata.',
            examBridge: 'Ajuda a reconhecer operacoes entre conjuntos mesmo quando a prova troca simbolos por regioes sombreadas.',
            gain: 'O aluno para de decorar nomes isolados e passa a enxergar o efeito de cada operacao no desenho.',
        },
        'conjuntos-3d-esferas': {
            whyHere: 'Mostra a inclusao N c Z c Q c R como camadas, reforcando a ideia de conjunto maior contendo o menor.',
            examBridge: 'Bom para itens de classificacao e hierarquia dos conjuntos numericos.',
            gain: 'Cria uma imagem mental de contenicao e abrangencia que reduz confusao entre elemento e subconjunto.',
        },
        'conjuntos-e-numeros': {
            whyHere: 'Faz a ponte entre teoria de conjuntos e classificacao de numeros concretos.',
            examBridge: 'Treina o aluno a escolher o conjunto mais especifico em questoes de alternativa.',
            gain: 'A leitura fica mais rapida porque cada exemplo passa a ser comparado por familia e nao por chute.',
        },
        'mapa-mental-numeros': {
            whyHere: 'O mapa entra aqui para dar panorama antes dos exercicios e reduzir a dependencia de memorizacao solta.',
            examBridge: 'Funciona bem na revisao de vespera para lembrar a cadeia N c Z c Q c R e os irracionais.',
            gain: 'Organiza os conjuntos em uma hierarquia visual simples, facil de revisar no celular.',
        },
        'quiz-conjuntos-numericos': {
            whyHere: 'O quiz reforca a passagem da teoria para a recuperacao rapida da resposta.',
            examBridge: 'Serve como aquecimento antes do quiz principal e antes de questoes de classificacao em prova.',
            gain: 'Mostra imediatamente onde a classificacao ainda falha e o que precisa ser retomado.',
        },
        'intervalos-reta-real': {
            whyHere: 'Intervalos so ficam claros quando a notacao e a reta aparecem juntas.',
            examBridge: 'Treina leitura de desigualdades e da notacao aberta, fechada e semiaberta.',
            gain: 'Reduz erro em colchetes, parenteses e no sentido dos extremos.',
        },
        'reta-real-construtor': {
            whyHere: 'Leva o aluno do simbolo para a manipulacao concreta da reta real.',
            examBridge: 'Bom para itens que pedem pertencimento de valores e leitura fina de extremos.',
            gain: 'Conecta simbolo, grafico e teste de valores sem depender de decoracao.',
        },
        'reta-real-3d': {
            whyHere: 'Este aprofundamento visual reforca a mesma ideia por outro angulo espacial.',
            examBridge: 'Ajuda a interpretar intervalos e semirretas em itens conceituais e graficos.',
            gain: 'Cria uma segunda rota mental para a mesma ideia, o que melhora a fixacao.',
        },
        'algebra-3d-superficie': {
            whyHere: 'A visualizacao em superficie liga expressao algebrica e comportamento geometrico.',
            examBridge: 'Apoia a leitura de mudancas em expressoes quadraticas e cubicas.',
            gain: 'A algebra deixa de parecer simbolo abstrato e passa a ter forma e resposta visual.',
        },
        'algebra-produtos-fatoracao': {
            whyHere: 'Este mapa combinado mostra que expandir e fatorar sao operacoes espelho.',
            examBridge: 'Excelente para revisao porque junta propriedades, produtos notaveis e fatoracao em um unico quadro.',
            gain: 'O aluno passa a ver a relacao entre estruturas em vez de estudar cada tema isolado.',
        },
        'expansor-produtos-notaveis': {
            whyHere: 'Explicita a origem de cada termo dos produtos notaveis.',
            examBridge: 'Reforca o desenvolvimento rapido de expressoes que aparece com frequencia em prova.',
            gain: 'Mostra de onde sai o termo do meio e por que o padrao se repete.',
        },
        'cubo-soma-3d': {
            whyHere: 'A versao 3D ajuda a dar corpo ao cubo da soma e a justificar os coeficientes repetidos.',
            examBridge: 'Bom para itens que pedem reconhecimento do padrao de (a+b)^3.',
            gain: 'Troca uma formula pesada por uma imagem de partes encaixadas que fica mais facil de recordar.',
        },
        'area-model-fatoracao': {
            whyHere: 'A area e a ponte concreta entre distributiva, expansao e fatoracao.',
            examBridge: 'Muito util para justificar quadrado da soma e diferenca de quadrados em prova.',
            gain: 'Mostra visualmente por que os termos aparecem e onde o 2ab nasce.',
        },
        'fatorador-visual': {
            whyHere: 'O foco aqui e ensinar a escolher a tecnica de fatoracao, nao so mostrar o resultado final.',
            examBridge: 'Treina fator comum, agrupamento e identidades em questoes de reconhecimento de padrao.',
            gain: 'Ajuda o aluno a decidir a estrategia antes de aplicar mecanicamente a conta.',
        },
        'bhaskara-animado': {
            whyHere: 'Une discriminante, raizes e leitura da parabola em uma so experiencia.',
            examBridge: 'Relaciona o calculo de Delta com o numero de raizes reais, algo muito cobrado em prova.',
            gain: 'Liga a formula ao grafico e aos tres casos principais de forma visual e memoravel.',
        },
        'parabola-raizes-3d': {
            whyHere: 'Aprofunda a intuicao grafica depois do Bhaskara animado e fecha a ponte com o eixo x.',
            examBridge: 'Ajuda a interpretar quando a curva toca, cruza ou nao cruza o eixo das raizes.',
            gain: 'Fixa o comportamento da funcao conforme os coeficientes mudam.',
        },
    },
};
